manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: inrumi
      url-base: https://github.com/inrumi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-config-totem
      remote: inrumi
      revision: chore/moduled-studiod
  self:
    path: config

